"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Schema for OGCAPI records profile for GeoDCAT - defines all extra elements defined by GeoDCAT so that the JSON-LD context can map to GeoDCAT RDF'
allOf:
  - $ref: ../geodcat-records/schema.json
  - $ref: bblocks://ogc.contrib.stac.item
  - { "description": "STAC core profile bound to GeoDCAT" }