identifier-prefix: ogc.geo.geodcat.

name: GeoDCAT implementation using OGC API Records
abstract: | 
  [OGC Building Blocks](https://ogcincubator.github.io/bblocks-docs/) linking GeoDCAT to OGC API Records and other schemas. Uses examples to support a development methodology for DCAT: separation of DCAT and other existing ontology from requirements identified from a range of alternative spatiotemporal metadata schemas.
description: |
  This is intended to explore and support regression testing during the development of GeoDCAT by testing that the concepts used in OGC API Records (and extensions such as STAC) can be mapped to either DCAT or added to GeoDCAT as required.
  
  For more information see the [GeoDCAT model development methdology](https://github.com/opengeospatial/GeoDCAT-SWG/blob/main/METHODOLOGY.md)
imports:
  - default
  - https://ogcincubator.github.io/bblocks-ogcapi-records/build/register.json
  - https://ogcincubator.github.io/bblocks-stac/build/register.json
  - https://ogcincubator.github.io/cross-domain-model
  # note that a PROV profile is intended as a key example of extending GeoDCAT
  # - https://ogcincubator.github.io/bblock-prov-schema/build/register.json





