"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Schema for my building block'
allOf:
  $ref: https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordGeoJSON.yaml
